// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	DoRequest
	DoResponse
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DoRequest struct {
	Do bool `protobuf:"varint,1,opt,name=do" json:"do,omitempty"`
}

func (m *DoRequest) Reset()                    { *m = DoRequest{} }
func (m *DoRequest) String() string            { return proto.CompactTextString(m) }
func (*DoRequest) ProtoMessage()               {}
func (*DoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DoRequest) GetDo() bool {
	if m != nil {
		return m.Do
	}
	return false
}

type DoResponse struct {
	Success bool `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *DoResponse) Reset()                    { *m = DoResponse{} }
func (m *DoResponse) String() string            { return proto.CompactTextString(m) }
func (*DoResponse) ProtoMessage()               {}
func (*DoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*DoRequest)(nil), "example.DoRequest")
	proto.RegisterType((*DoResponse)(nil), "example.DoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TokenAPIExample service

type TokenAPIExampleClient interface {
	Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoResponse, error)
}

type tokenAPIExampleClient struct {
	cc *grpc.ClientConn
}

func NewTokenAPIExampleClient(cc *grpc.ClientConn) TokenAPIExampleClient {
	return &tokenAPIExampleClient{cc}
}

func (c *tokenAPIExampleClient) Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoResponse, error) {
	out := new(DoResponse)
	err := grpc.Invoke(ctx, "/example.TokenAPIExample/Do", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TokenAPIExample service

type TokenAPIExampleServer interface {
	Do(context.Context, *DoRequest) (*DoResponse, error)
}

func RegisterTokenAPIExampleServer(s *grpc.Server, srv TokenAPIExampleServer) {
	s.RegisterService(&_TokenAPIExample_serviceDesc, srv)
}

func _TokenAPIExample_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenAPIExampleServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.TokenAPIExample/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenAPIExampleServer).Do(ctx, req.(*DoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenAPIExample_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.TokenAPIExample",
	HandlerType: (*TokenAPIExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _TokenAPIExample_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xa4, 0xb9,
	0x38, 0x5d, 0xf2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x52, 0xf2,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x82, 0x98, 0x52, 0xf2, 0x95, 0xd4, 0xb8, 0xb8, 0x40, 0x92,
	0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0xc5, 0xa5, 0xc9, 0xc9, 0xa9, 0xc5,
	0xc5, 0x12, 0x4c, 0x60, 0x25, 0x30, 0xae, 0x91, 0x13, 0x17, 0x7f, 0x48, 0x7e, 0x76, 0x6a, 0x9e,
	0x63, 0x80, 0xa7, 0x2b, 0xc4, 0x5c, 0x21, 0x7d, 0x2e, 0x26, 0x97, 0x7c, 0x21, 0x21, 0x3d, 0x98,
	0xb5, 0x70, 0x4b, 0xa4, 0x84, 0x51, 0xc4, 0x20, 0x66, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0x1d, 0x66,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x7a, 0x85, 0xd1, 0xa9, 0x00, 0x00, 0x00,
}
